
OBJECTS += $(WORKSPACE_PATH)lua/lapi.o $(WORKSPACE_PATH)lua/lcode.o $(WORKSPACE_PATH)lua/ldebug.o $(WORKSPACE_PATH)lua/ldo.o $(WORKSPACE_PATH)lua/ldump.o \
$(WORKSPACE_PATH)lua/lfunc.o $(WORKSPACE_PATH)lua/lgc.o $(WORKSPACE_PATH)lua/llex.o $(WORKSPACE_PATH)lua/lmem.o $(WORKSPACE_PATH)lua/lobject.o $(WORKSPACE_PATH)lua/lopcodes.o \
$(WORKSPACE_PATH)lua/lparser.o $(WORKSPACE_PATH)lua/lstate.o $(WORKSPACE_PATH)lua/lstring.o $(WORKSPACE_PATH)lua/ltable.o $(WORKSPACE_PATH)lua/ltm.o  \
$(WORKSPACE_PATH)lua/lundump.o $(WORKSPACE_PATH)lua/lvm.o $(WORKSPACE_PATH)lua/lzio.o $(WORKSPACE_PATH)lua/lrotable.o $(WORKSPACE_PATH)lua/lauxlib.o $(WORKSPACE_PATH)lua/lbaselib.o \
$(WORKSPACE_PATH)lua/ldblib.o $(WORKSPACE_PATH)lua/liolib.o $(WORKSPACE_PATH)lua/lmathlib.o $(WORKSPACE_PATH)lua/loslib.o $(WORKSPACE_PATH)lua/ltablib.o \
$(WORKSPACE_PATH)lua/lstrlib.o $(WORKSPACE_PATH)lua/loadlib.o $(WORKSPACE_PATH)lua/linit.o $(WORKSPACE_PATH)lua/print.o $(WORKSPACE_PATH)lua/linenoise.o

INCLUDE_PATHS += -I$(WORKSPACE_PATH)lua